### PR TITLE
Add support for dump and listing files

### LINKED ISSUE #328: FR: add support for dump and list files
See https://github.com/gnucobol/vscode_cobol4gnucobol/blob/main/package.json - as the license for the vscode extension here is MIT and the same applies to the referenced repo any definitions can even be copied completely.

This is about recognition, syntax highlighting and outline.

### PR DESCRIPTION
**Pull request by nberth**
Closes #328 & #348

### CODE REVIEW

**Comment by GitMensch** [comment]
Does this include the use of the LSP on those (outline based on this file only)? Otherwise this may only be a partial solve of the referenced issue.

**Comment by nberth** [comment]
> Does this include the use of the LSP on those (outline based on this file only)? Otherwise this may only be a partial solve of the referenced issue.

Not yet, this is only preliminary support; I'll add a separate issue for the outline.

**Review by emilienlemaire — APPROVED** [review]

**Comment by nberth** [comment]
> > Does this include the use of the LSP on those (outline based on this file only)? Otherwise this may only be a partial solve of the referenced issue.
> 
> Not yet, this is only preliminary support; I'll add a separate issue for the outline.

Actually that was much more easy to do than I anticipated ;-)

**Review by emilienlemaire — APPROVED** [review]

**Comment by nberth** [comment]
@GitMensch Note: this currently hardcodes the format for listing and dump files to an equivalent of `-fformat=VARIABLE`. If such files may include lines longer than 250 chars, then maybe we'd need another source-format with no right margin at all.

**Comment by GitMensch** [comment]
Nice. I'll check once the CI vsix exists, or when there is another binary available.

**Comment by GitMensch** [comment]
Things to check: wide and normal listing -T and -t along with/without symbols and -Xref.

**Pull request merged**
