### PR TITLE
Fix broken link + add wiki link

### PR DESCRIPTION
**Pull request by emilienlemaire**

### CODE REVIEW

**Review by nberth — COMMENTED** [review]
For emacs we have a README inside the `emacs`  subfolder. I'm not sure what using a wiki page would bring (apart from requirements to moderate via other means than PRs, maybe — which we may not want).

(Note I'm currently adjusting this README and filling in the Changelog up to version 0.1.1)

**Comment by emilienlemaire** [comment]
Well the github wiki is an easy place to find, and in my experience one of the first place to look for a bit of info, the documentation comes second when checking the capabilities and features of the program

**Comment by emilienlemaire** [comment]
> (Note I'm currently adjusting this README and filling in the Changelog up to version 0.1.1)

Then you might close this PR, just add the changes I've made to your edits

**Comment by nberth** [comment]
> Well the github wiki is an easy place to find, and in my experience one of the first place to look for a bit of info, the documentation comes second when checking the capabilities and features of the program

I never usually find anything up-to-date in these wikis.
Keeping these docs under version control is the minimal requirement that I think those pages don't offer.

**Comment by nberth** [comment]
Closing as superseded by #277

**Pull request closed without merging**
