### PR TITLE
Add  SQL preprocessor

### PR DESCRIPTION
**Pull request by LilyOlivier**

### CODE REVIEW

**Comment by GitMensch** [comment]
Nice one, do you mind to rebase?

**Comment by GitMensch** [comment]
Can you share what the state of this PR is / what is missing?
It seems the COBOL test files have no automated testing applied so far, right?

**Comment by LilyOlivier** [comment]
Yes, the preprocessor is not finished yet. There are still many case that are not correctly preprocessed. The goal is to use GixSQL's runtime.

**Comment by nberth** [comment]
Closing in favor of #370.

**Pull request closed without merging**
