### PR TITLE
Better config UX

### PR DESCRIPTION
**Pull request by nberth**
Included changes mostly include:
- Early loading of project caches upon startup (when the LSP client/VS Code provides a list of workspace directories);
- Use of VS Code's settings to configure projects in the LSP server;
- A new command to save the current VS Code configuration to a `superbol.toml`, for each project directory opened in a workspace. Once this file exists, changes to VS Code's settings are ignored (but trigger a warning to the user).

### CODE REVIEW

**Comment by engboris** [comment]
How do you save the VSCode configurations to a `superbol.toml` file (from the VSCode UI)?

I don't see any warning when creating a `superbol.toml` file.

**Comment by nberth** [comment]
> How do you save the VSCode configurations to a `superbol.toml` file (from the VSCode UI)?

You should have a dedicated command `SuperBOL: Write Configuration File` (or a similar name).

> I don't see any warning when creating a `superbol.toml` file.

You should see a warning if you edit VS  Code project settings (everything that belongs to section `superbol.cobol`) *after* the `superbol.toml` has been created.

**Review by engboris — DISMISSED** [review]

**Comment by engboris** [comment]
I just noticed that the data written on `superbol.toml` after using the command does not match the VSCode configuration. I always get the same config file:
```toml

#SuperBOL project configuration
[cobol]

#Default dialect for COBOL source files
dialect = "default"

#Default source reference-format
source-format = "auto"
[[cobol.copybooks]]
file-relative = false
dir = "."

#Indenter configuration
[cobol.indent]
```

**Comment by engboris** [comment]
What I tried was to start with no `superbol.toml`. Change the configuration on VSCode and run the `SuperBOL: Write Project Configuration command` (dialect and format). A new `superbol.toml` file is created but it is a default one not following the previous configuration.

**Comment by nberth** [comment]
> What I tried was to start with no `superbol.toml`. Change the configuration on VSCode and run the `SuperBOL: Write Project Configuration command` (dialect and format). A new `superbol.toml` file is created but it is a default one not following the previous configuration.

I just re-checked and got the proper result. Do you have several directories in the workspace?

**Comment by engboris** [comment]
I did `code .` on `gnucobol-contrib/samples/worldcities/`. I just have a `_superbol` directory.

**Comment by nberth** [comment]
> I did `code .` on `gnucobol-contrib/samples/worldcities/`. I just have a `_superbol` directory.

Oh, did you have a file openned?

**Comment by engboris** [comment]
I had `worldcities0.cbl`, `worldcities2.cbl`, `worldcities3.cbl` and the settings opened.

**Comment by engboris** [comment]
I also tested with only the settings opened and the `superbol.toml` file is not created at all.

**Comment by nberth** [comment]
> I also tested with only the settings opened and the `superbol.toml` file is not created at all.

Yes at the moment one file from the project needs to be opened to decide in which project the `superbol.toml` file needs to be written. Could change that to "whatever opened" project, but that could be too invasive maybe.

**Comment by engboris** [comment]
Here is the output I get for the LSP (Ctrl+K, Ctrl+H and select SuperBOL Language Server):

> SuperBOL, by OCamlPro. https://get-superbol.com. Affero GPL version.
[Info  - 16:03:04] Initializing for workspace folders: /home/engboris/gnucobol-contrib/samples/worldcities
[Info  - 16:03:04] Negociated server parameters:
{ client_config_watcher: true
  client_file_watcher: true }
[Info  - 16:03:04] Successfully read project cache for file:///home/engboris/gnucobol-contrib/samples/worldcities
[Info  - 16:03:04] Successfully read document cache for file:///home/engboris/gnucobol-contrib/samples/worldcities/worldcities3.cbl
[Error - 16:03:04] Exception raised in delayed computation: Configuration file `cobol2002.conf' not found (search path: /home/engboris/gnucobol-contrib/samples/worldcities:/home/engboris/.config/superbol)
src/lsp/cobol_ptree/misc_sections_visitor.ml:243:
  (Cobol_ptree__Misc_sections_visitor.fold_configuration_section): partial
  visitor implementation
src/lsp/cobol_ptree/misc_sections_visitor.ml:72:
  (Cobol_ptree__Misc_sections_visitor.fold_select_clause): missing visitor
  implementation
src/lsp/cobol_ptree/data_sections_visitor.ml:276:
  (Cobol_ptree__Data_sections_visitor.fold_file_section): missing visitor
  implementation
src/lsp/cobol_ptree/data_sections_visitor.ml:227:
  (Cobol_ptree__Data_sections_visitor.fold_data_clause): partial visitor
  implementation
Updated file `/home/engboris/gnucobol-contrib/samples/worldcities/superbol.toml'
[Info  - 16:03:14] Saving configuration for project of URI file:///home/engboris/gnucobol-contrib/samples/worldcities/worldcities0.cbl
src/lsp/cobol_ptree/statements_visitor.ml:661:
  (Cobol_ptree__Statements_visitor.fold_statement): partial visitor
  implementation
[Error - 16:04:18] Exception raised in delayed computation: Configuration file `cobol2002.conf' not found (search path: /home/engboris/gnucobol-contrib/samples/worldcities:/home/engboris/.config/superbol)
[Info  - 16:06:40] Saving configuration for project of URI file:///home/engboris/gnucobol-contrib/samples/worldcities/all.sh
Updated file `/home/engboris/gnucobol-contrib/samples/worldcities/superbol.toml'
[Error - 16:06:59] Exception raised in delayed computation: Configuration file `cobol2002.conf' not found (search path: /home/engboris/gnucobol-contrib/samples/worldcities:/home/engboris/.config/superbol)
[Info  - 16:07:09] Saving configuration for project of URI file:///home/engboris/gnucobol-contrib/samples/worldcities/worldcities0.cbl
Updated file `/home/engboris/gnucobol-contrib/samples/worldcities/superbol.toml'

**Comment by engboris** [comment]
Problem solved with `COB_CONFIG_DIR=<config-dir-of-gnucobol> code <dir>`, which is apparently unrelated to this PR.

**Review by engboris — APPROVED** [review]

**Pull request merged**
